# Generated by Django 5.1.5 on 2025-02-05 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agency", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newspaper",
            options={"ordering": ["-published_date"]},
        ),
        migrations.RemoveField(
            model_name="newspaper",
            name="topic",
        ),
        migrations.AlterField(
            model_name="redactor",
            name="years_of_experience",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name="newspaper",
            name="topic",
            field=models.ManyToManyField(related_name="articles", to="agency.topic"),
        ),
    ]
